// Country name to ISO code mapping
const countryNameToId = {
  'United States': 'US',
  'United States of America': 'US',
  'U.S.A.': 'US',
  USA: 'US',
  Canada: 'CA',
  Mexico: 'MX',
  Brazil: 'BR',
  Argentina: 'AR',
  'United Kingdom': 'GB',
  UK: 'GB',
  'Great Britain': 'GB',
  France: 'FR',
  Germany: 'DE',
  Italy: 'IT',
  Spain: 'ES',
  China: 'CN',
  "People's Republic of China": 'CN',
  India: 'IN',
  Australia: 'AU',
  Japan: 'JP',
  'South Africa': 'ZA',
  Afghanistan: 'AF',
  Albania: 'AL',
  Algeria: 'DZ',
  Andorra: 'AD',
  Angola: 'AO',
  'Antigua and Barbuda': 'AG',
  Armenia: 'AM',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahamas: 'BS',
  Bahrain: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Belarus: 'BY',
  Belgium: 'BE',
  Belize: 'BZ',
  Benin: 'BJ',
  Bhutan: 'BT',
  Bolivia: 'BO',
  'Bosnia and Herzegovina': 'BA',
  Botswana: 'BW',
  'Brunei Darussalam': 'BN',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  'Cabo Verde': 'CV',
  'Cape Verde': 'CV',
  Cambodia: 'KH',
  Cameroon: 'CM',
  'Central African Republic': 'CF',
  Chad: 'TD',
  Chile: 'CL',
  Colombia: 'CO',
  Comoros: 'KM',
  'Congo (Brazzaville)': 'CG',
  'Republic of the Congo': 'CG',
  'Congo (Kinshasa)': 'CD',
  'Democratic Republic of the Congo': 'CD',
  'Costa Rica': 'CR',
  Croatia: 'HR',
  Cuba: 'CU',
  Cyprus: 'CY',
  Czechia: 'CZ',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  Djibouti: 'DJ',
  Dominica: 'DM',
  'Dominican Republic': 'DO',
  Ecuador: 'EC',
  Egypt: 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  Eritrea: 'ER',
  Estonia: 'EE',
  Eswatini: 'SZ',
  Swaziland: 'SZ',
  Ethiopia: 'ET',
  Fiji: 'FJ',
  Finland: 'FI',
  Gabon: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Ghana: 'GH',
  Greece: 'GR',
  Grenada: 'GD',
  Guatemala: 'GT',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  Guyana: 'GY',
  Haiti: 'HT',
  Honduras: 'HN',
  Hungary: 'HU',
  Iceland: 'IS',
  Indonesia: 'ID',
  Iran: 'IR',
  Iraq: 'IQ',
  Ireland: 'IE',
  Israel: 'IL',
  'Ivory Coast': 'CI',
  "Côte d'Ivoire": 'CI',
  Jamaica: 'JM',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Kiribati: 'KI',
  'North Korea': 'KP',
  "Democratic People's Republic of Korea": 'KP',
  'South Korea': 'KR',
  'Republic of Korea': 'KR',
  Kuwait: 'KW',
  Kyrgyzstan: 'KG',
  'Lao PDR': 'LA',
  Laos: 'LA',
  Latvia: 'LV',
  Lebanon: 'LB',
  Lesotho: 'LS',
  Liberia: 'LR',
  Libya: 'LY',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Madagascar: 'MG',
  Malawi: 'MW',
  Malaysia: 'MY',
  Maldives: 'MV',
  Mali: 'ML',
  Malta: 'MT',
  'Marshall Islands': 'MH',
  Mauritania: 'MR',
  Mauritius: 'MU',
  Micronesia: 'FM',
  'Federated States of Micronesia': 'FM',
  Moldova: 'MD',
  Monaco: 'MC',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Morocco: 'MA',
  Mozambique: 'MZ',
  Myanmar: 'MM',
  Burma: 'MM',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Nicaragua: 'NI',
  Niger: 'NE',
  Nigeria: 'NG',
  'North Macedonia': 'MK',
  Macedonia: 'MK',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Palau: 'PW',
  Palestine: 'PS',
  'State of Palestine': 'PS',
  Panama: 'PA',
  'Papua New Guinea': 'PG',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Poland: 'PL',
  Portugal: 'PT',
  Qatar: 'QA',
  Romania: 'RO',
  'Russian Federation': 'RU',
  Russia: 'RU',
  Rwanda: 'RW',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Vincent and the Grenadines': 'VC',
  Samoa: 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  Senegal: 'SN',
  Serbia: 'RS',
  Seychelles: 'SC',
  'Sierra Leone': 'SL',
  Singapore: 'SG',
  Slovakia: 'SK',
  'Slovak Republic': 'SK',
  Slovenia: 'SI',
  'Solomon Islands': 'SB',
  Somalia: 'SO',
  'South Sudan': 'SS',
  'Sri Lanka': 'LK',
  Sudan: 'SD',
  Suriname: 'SR',
  Sweden: 'SE',
  Switzerland: 'CH',
  'Syrian Arab Republic': 'SY',
  Syria: 'SY',
  Taiwan: 'TW',
  'Republic of China': 'TW',
  Tajikistan: 'TJ',
  Tanzania: 'TZ',
  Thailand: 'TH',
  'Timor-Leste': 'TL',
  'East Timor': 'TL',
  Togo: 'TG',
  Tonga: 'TO',
  'Trinidad and Tobago': 'TT',
  Tunisia: 'TN',
  Turkey: 'TR',
  Turkmenistan: 'TM',
  Tuvalu: 'TV',
  Uganda: 'UG',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  UAE: 'AE',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  Vanuatu: 'VU',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Yemen: 'YE',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
  'Åland Islands': 'AX',
  'American Samoa': 'AS',
  Anguilla: 'AI',
  Aruba: 'AW',
  Bermuda: 'BM',
  Bonaire: 'BQ',
  'Bouvet Island': 'BV',
  'British Indian Ocean Territory': 'IO',
  'British Virgin Islands': 'VG',
  'Cayman Islands': 'KY',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  'Cook Islands': 'CK',
  Curaçao: 'CW',
  'Falkland Islands': 'FK',
  'Faroe Islands': 'FO',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  Gibraltar: 'GI',
  Greenland: 'GL',
  Guadeloupe: 'GP',
  Guam: 'GU',
  Guernsey: 'GG',
  'Heard Island and McDonald Islands': 'HM',
  'Hong Kong': 'HK',
  'Isle of Man': 'IM',
  Jersey: 'JE',
  Macao: 'MO',
  Martinique: 'MQ',
  Mayotte: 'YT',
  Montserrat: 'MS',
  'New Caledonia': 'NC',
  Niue: 'NU',
  'Norfolk Island': 'NF',
  'Northern Mariana Islands': 'MP',
  Pitcairn: 'PN',
  'Puerto Rico': 'PR',
  Réunion: 'RE',
  'Saint Barthélemy': 'BL',
  'Saint Helena': 'SH',
  'Saint Martin': 'MF',
  'Saint Pierre and Miquelon': 'PM',
  'Sint Maarten': 'SX',
  'South Georgia and the South Sandwich Islands': 'GS',
  'Svalbard and Jan Mayen': 'SJ',
  Tokelau: 'TK',
  'Turks and Caicos Islands': 'TC',
  'U.S. Minor Outlying Islands': 'UM',
  'U.S. Virgin Islands': 'VI',
  'Vatican City': 'VA',
  'Holy See': 'VA',
  'Wallis and Futuna': 'WF',
  'Western Sahara': 'EH',
};

export default countryNameToId;
